/// Chances to be afflicted
#define COSMIC_RADIATION_CHANCE_LOW 1
#define COSMIC_RADIATION_CHANCE_MEDIUM 3
#define COSMIC_RADIATION_CHANCE_HIGH 8
#define COSMIC_RADIATION_CHANCE_VERY_HIGH 15

/// Chances to be healed
#define COSMIC_RADIATION_CHANCE_HEAL_LOW 33
#define COSMIC_RADIATION_CHANCE_HEAL_MEDIUM 50
#define COSMIC_RADIATION_CHANCE_HEAL_HIGH 75

/// Upper magnitudes
#define COSMIC_RADIATION_BRACKET_LOW 15
#define COSMIC_RADIATION_BRACKET_MEDIUM 25
#define COSMIC_RADIATION_BRACKET_HIGH 50

#define COSMIC_RADIATION_BRACKET_HEAL -1

/// Damage strengths
#define COSMIC_RADIATION_TICK_LOW 5
#define COSMIC_RADIATION_TICK_MEDIUM 8
#define COSMIC_RADIATION_TICK_HIGH 12

/// Heal strengths
#define COSMIC_RADIATION_HEAL_LOW -10
#define COSMIC_RADIATION_HEAL_MEDIUM -15
#define COSMIC_RADIATION_HEAL_HIGH -30
